### ISSUE TITLE
Missing definition for Application [A] tech stack

### ISSUE THREAD

**Issue by asa1997** [Be-Secure/Be-Secure#44]
Missing definition for Application [A] tech stack under [tech stack](https://be-secure.github.io/Be-Secure/tech_stack.html) details in the webpage.

![Screenshot from 2021-09-09 10-47-12](https://user-images.githubusercontent.com/58501088/132627079-56e8bd85-8a5b-4ae9-ac70-2bcebccff8e7.png)

**Comment by jobyko** [comment]
Updated the page with requested definition.
